name: beifa_app_platform
description: 贝发集团智能产品APP导航平台

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  dio: ^5.3.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/beifa_logo.png
    - assets/images/featured_banner_bg.png
    - assets/images/translate_icon.png
    - assets/images/logo/1.png
    - assets/images/logo/2.png
    - assets/images/logo/3.png
    - assets/images/logo/4.png
    - assets/images/logo/5.png
    - assets/images/listBg/1.png
    - assets/images/listBg/2.png
    - assets/images/listBg/3.png
    - assets/images/listBg/4.png
    - assets/images/listBg/5.png
    - assets/images/productImages/origins/zh/1.png
    - assets/images/productImages/origins/zh/2.png
    - assets/images/productImages/origins/zh/3.png
    - assets/images/productImages/origins/zh/4.png
    - assets/images/productImages/futora/zh/1.png
    - assets/images/productImages/futora/zh/2.png
    - assets/images/productImages/futora/zh/3.png
    - assets/images/productImages/fitCloudPro/zh/1.png
    - assets/images/productImages/fitCloudPro/zh/2.png
    - assets/images/productImages/fitCloudPro/zh/3.png
    - assets/images/productImages/danaID/zh/1.png
    - assets/images/productImages/danaID/zh/2.png
    - assets/images/productImages/danaID/zh/3.png
    - assets/images/productImages/danaID/zh/4.png
    - assets/images/productImages/nebulabuds/zh/1.png
    - assets/images/productImages/nebulabuds/zh/2.png
    - assets/images/productImages/nebulabuds/zh/3.png
    - assets/images/productImages/nebulabuds/zh/4.png
  # fonts:
  #   - family: PingFang
  #     fonts:
  #       - asset: assets/fonts/PingFang-Regular.ttf
  #       - asset: assets/fonts/PingFang-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/PingFang-Bold.ttf
  #         weight: 700

